// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chodhjjqugvcqbjhjsjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNob2RoampxdWd2Y3Fiamhqc2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDY2ODEsImV4cCI6MjA3MDUyMjY4MX0.OOvznRs2aiybEBoGC2QpQ6FgBgldjPWeI4ByMRkG4Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});